# Generated by Django 5.2.13 on 2026-09-08 23:17

from django.db import migrations, models


def rename_basic_to_starter(apps, schema_editor):
    """Le plan BASIC est renommé STARTER (spec monétisation §11).

    Convertit les instantanés stockés pour garder un historique cohérent :
    les abonnements de vendeurs et les lignes de ventes déjà ventilées ne
    doivent pas conserver une valeur obsolète.
    """
    SellerSubscription = apps.get_model("commissions", "SellerSubscription")
    CommissionTransaction = apps.get_model("commissions", "CommissionTransaction")
    SellerSubscription.objects.filter(plan="BASIC").update(plan="STARTER")
    CommissionTransaction.objects.filter(plan="BASIC").update(plan="STARTER")


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_basic_to_starter, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sellersubscription',
            name='plan',
            field=models.CharField(blank=True, choices=[('STARTER', 'STARTER'), ('PRO', 'PRO'), ('BUSINESS', 'BUSINESS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sellersubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
    ]
