# Generated by Django 5.0.14 on 2026-09-08 12:00
# Étend les choix du champ `name` du modèle Role avec les rôles
# d'administration spécialisés du centre de contrôle (spec §42).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_phone_verified_user_phone_verified_at_phoneotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("super_admin", "Super Administrateur"),
                    ("admin_kyc", "Admin KYC"),
                    ("admin_support", "Admin Support"),
                    ("admin_finance", "Admin Finance"),
                    ("admin_marketplace", "Admin Marketplace"),
                    ("admin_delivery", "Admin Livraison"),
                    ("merchant", "Commerçant"),
                    ("client", "Client"),
                    ("driver", "Livreur"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]