# Generated by Django 5.2.13 on 2026-09-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('super_admin', 'Super Administrateur'), ('admin_kyc', 'Admin KYC'), ('admin_support', 'Admin Support'), ('admin_finance', 'Admin Finance'), ('admin_marketplace', 'Admin Marketplace'), ('admin_delivery', 'Admin Livraison'), ('merchant', 'Commerçant'), ('client', 'Client'), ('driver', 'Livreur'), ('partner', 'Partenaire de livraison')], max_length=100, unique=True),
        ),
    ]
