# Generated by Django 5.0.14 on 2026-10-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="type",
            field=models.CharField(
                choices=[
                    ("email_verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("guest_login", "Guest Login Link"),
                ],
                max_length=50,
            ),
        ),
    ]
