# Generated by Django 5.2.13 on 2026-09-08 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('backup_type', models.CharField(choices=[('database', 'Base de données'), ('files', 'Fichiers / documents'), ('full', 'Sauvegarde complète')], default='database', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('success', 'Réussie'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'verbose_name_plural': 'Sauvegardes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=100)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('environment', models.CharField(default='production', max_length=50)),
                ('status', models.CharField(choices=[('deploying', 'Déploiement en cours'), ('deployed', 'Déployé'), ('active', 'Actif (courant)'), ('rolled_back', 'Restauré (rollback)'), ('failed', 'Échec')], default='deployed', max_length=30)),
                ('is_active', models.BooleanField(default=False, help_text='Version actuellement en production')),
                ('notes', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version déployée',
                'verbose_name_plural': 'Versions déployées',
                'ordering': ['-deployed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Motif court (ex. « Contournement mode maintenance »)', max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('scopes', models.JSONField(default=list, help_text="Liste des périmètres ouverts (ex. ['ops.manage', 'settings.manage'])")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('revoked', 'Révoqué')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Accès d'urgence",
                'verbose_name_plural': "Accès d'urgence",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('major', 'Majeur'), ('minor', 'Mineur'), ('info', 'Informatif')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('investigating', "En cours d'analyse"), ('identified', 'Cause identifiée'), ('mitigating', 'Atténuation en cours'), ('resolved', 'Résolu'), ('closed', 'Clos')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('json', 'JSON'), ('boolean', 'Booléen'), ('integer', 'Entier'), ('string', 'Texte')], default='json', max_length=20)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('is_flag', models.BooleanField(default=False, help_text="Feature flag affiché comme toggle dans l'UI")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre de plateforme',
                'verbose_name_plural': 'Paramètres de plateforme',
                'ordering': ['key'],
            },
        ),
    ]
