# Generated by Django 5.2.13 on 2026-09-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGE', 'Changement de mot de passe'), ('PHONE_CHANGE', 'Changement de numéro de téléphone'), ('PAYMENT_INFO_CHANGE', "Changement d'information de paiement"), ('KYC_DOCUMENT_UPLOAD', "Dépôt de document d'identité"), ('KYC_APPROVED', "Dossier d'identité validé"), ('KYC_REJECTED', "Dossier d'identité refusé"), ('KYC_REQUEST_RESUBMISSION', 'Nouvelle soumission demandée'), ('KYC_SUSPENDED', 'Compte vendeur suspendu'), ('KYC_BLOCKED', 'Compte vendeur bloqué'), ('PAYOUT_REQUEST', "Demande de retrait d'argent"), ('FRAUD_FLAG', 'Signalement de fraude probable')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de sécurité',
                'verbose_name_plural': 'Journal de sécurité',
                'ordering': ['-created_at'],
            },
        ),
    ]
