# Generated by Django 5.0.14 on 2026-09-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="confirmation_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="delivery",
            name="confirmation_otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="confirmation_otp_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
