# Generated by Django 5.0.14 on 2026-09-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_delivery_confirmation_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="last_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="last_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="position_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
