# Generated by Django 5.2.13 on 2026-09-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_driver_last_latitude_driver_last_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at']},
        ),
    ]
