# Generated by Django 5.2.13 on 2026-09-09 21:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_admin_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='delivery',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failure_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('customer_absent', 'Client absent'), ('number_unreachable', 'Numéro inaccessible'), ('wrong_address', 'Mauvaise adresse'), ('customer_refused', 'Client refuse'), ('package_damaged', 'Colis endommagé'), ('transport_issue', 'Problème de transport'), ('other', 'Autre')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_method',
            field=models.CharField(blank=True, choices=[('otp', 'OTP'), ('signature', 'Signature'), ('photo', 'Photo'), ('client_confirmation', 'Confirmation client')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='delivery',
            name='proof_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='refuse_reason',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('customer_absent', 'Client absent'), ('customer_refused', 'Client refuse'), ('wrong_address', 'Mauvaise adresse'), ('package_damaged', 'Colis endommagé'), ('shipping_error', "Erreur d'envoi"), ('other', 'Autre')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='max_active_deliveries',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('pickup_pending', 'Pickup Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('customer_unavailable', 'Customer Unavailable'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('action', models.CharField(max_length=50)),
                ('previous_status', models.CharField(blank=True, default='', max_length=50)),
                ('new_status', models.CharField(blank=True, default='', max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.delivery')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('inactive', 'Inactif'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='inactive', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('api_key_hash', models.CharField(blank=True, default='', max_length=64)),
                ('api_key_last4', models.CharField(blank=True, default='', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='orders.deliverypartner'),
        ),
        migrations.AddField(
            model_name='driver',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='orders.deliverypartner'),
        ),
        migrations.CreateModel(
            name='PartnerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de paiement'), ('paid', 'Payée'), ('contested', 'Contestée')], default='draft', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('marketplace_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('on_demand_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('marketplace_deliveries_count', models.PositiveIntegerField(default=0)),
                ('on_demand_deliveries_count', models.PositiveIntegerField(default=0)),
                ('marketplace_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('on_demand_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('collection_fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('recon_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('recon_diff', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('recon_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='orders.deliverypartner')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PartnerZonePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_fee', models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=10)),
                ('partner_cost', models.DecimalField(decimal_places=2, default=Decimal('1500'), max_digits=10)),
                ('estimated_delay_minutes', models.PositiveIntegerField(default=60)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_pricings', to='orders.deliverypartner')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_pricings', to='orders.deliveryzone')),
            ],
            options={
                'ordering': ['zone__name'],
                'unique_together': {('partner', 'zone')},
            },
        ),
    ]
