# Generated by Django 5.2.13 on 2026-09-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerkyc',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sellerkyc',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='driverkyc',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='kycauditlog',
            name='action',
            field=models.CharField(choices=[('ADMIN_VIEW_SELLER_KYC', 'ADMIN_VIEW_SELLER_KYC'), ('ADMIN_VIEW_DRIVER_KYC', 'ADMIN_VIEW_DRIVER_KYC'), ('ADMIN_APPROVE_SELLER_KYC', 'ADMIN_APPROVE_SELLER_KYC'), ('ADMIN_APPROVE_DRIVER_KYC', 'ADMIN_APPROVE_DRIVER_KYC'), ('ADMIN_REJECT_SELLER_KYC', 'ADMIN_REJECT_SELLER_KYC'), ('ADMIN_REJECT_DRIVER_KYC', 'ADMIN_REJECT_DRIVER_KYC'), ('ADMIN_REVIEW_SELLER_KYC', 'ADMIN_REVIEW_SELLER_KYC'), ('ADMIN_REVIEW_DRIVER_KYC', 'ADMIN_REVIEW_DRIVER_KYC'), ('ADMIN_RESUBMIT_SELLER_KYC', 'ADMIN_RESUBMIT_SELLER_KYC'), ('ADMIN_RESUBMIT_DRIVER_KYC', 'ADMIN_RESUBMIT_DRIVER_KYC'), ('ADMIN_SUSPEND_SELLER_KYC', 'ADMIN_SUSPEND_SELLER_KYC'), ('ADMIN_SUSPEND_DRIVER_KYC', 'ADMIN_SUSPEND_DRIVER_KYC'), ('ADMIN_BLOCK_SELLER_KYC', 'ADMIN_BLOCK_SELLER_KYC'), ('ADMIN_BLOCK_DRIVER_KYC', 'ADMIN_BLOCK_DRIVER_KYC')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerkyc',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='kyc.sellerkyc')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
