# Generated by Django 5.0.14 on 2026-09-10 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0012_subscription_reference"),
        ("orders", "0007_deliverypricingrule_and_more"),
        ("payments", "0004_admin_center"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="payment_targets_order_xor_subscription",
        ),
        migrations.AddField(
            model_name="payment",
            name="global_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.globalorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("global_order__isnull", True),
                        ("order__isnull", False),
                        ("subscription__isnull", True),
                    ),
                    models.Q(
                        ("global_order__isnull", False),
                        ("order__isnull", True),
                        ("subscription__isnull", True),
                    ),
                    models.Q(
                        ("global_order__isnull", True),
                        ("order__isnull", True),
                        ("subscription__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="payment_targets_one_billing_object",
            ),
        ),
    ]
