# Generated by Django 5.2.13 on 2026-09-11 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_payment_targets_order_xor_subscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at']},
        ),
    ]
