# Generated by Django 5.2.13 on 2026-09-08 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0009_seed_store_categories'),
        ('orders', '0005_admin_center'),
        ('payments', '0004_admin_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('category', models.CharField(choices=[('order_not_received', 'Commande non reçue'), ('wrong_item', 'Article incorrect'), ('defective_product', 'Produit défectueux'), ('late_delivery', 'Livraison en retard'), ('damaged_during_delivery', 'Colis endommagé à la livraison'), ('incorrect_charge', 'Montant prélevé incorrect'), ('refund_issue', 'Problème de remboursement'), ('seller_behavior', 'Comportement du vendeur'), ('driver_behavior', 'Comportement du livreur'), ('quality_issue', 'Problème de qualité'), ('subscription_issue', "Problème d'abonnement"), ('other', 'Autre')], default='other', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('assigned', 'Assignée'), ('in_progress', 'En cours de traitement'), ('escalated', 'Escaladée'), ('resolved', 'Résolue'), ('closed', 'Clos')], default='open', max_length=20)),
                ('resolution_decision', models.CharField(blank=True, choices=[('refund', 'Remboursement'), ('exchange', 'Remplacement / échange'), ('return', 'Retour produit'), ('compensation', 'Indemnisation'), ('info', 'Information donnée'), ('no_action', 'Aucune action requise')], max_length=30)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.delivery')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.driver')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='payments.payment')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='catalog.store')),
            ],
            options={
                'verbose_name': 'Plainte',
                'verbose_name_plural': 'Plaintes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('storage_key', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintTimeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Déposée'), ('assigned', 'Assignée'), ('started', 'Traitement commencé'), ('escalated', 'Escaladée'), ('responded', 'Réponse apportée'), ('resolved', 'Résolue'), ('closed', 'Clos'), ('reopened', 'Rouverte'), ('note', 'Note interne')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Étape de plainte',
                'verbose_name_plural': 'Étapes de plainte',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('category', models.CharField(choices=[('question', 'Question'), ('help', 'Aide / assistance'), ('account', 'Problème de compte'), ('payment', 'Paiement'), ('subscription', 'Abonnement'), ('tech', 'Problème technique'), ('other', 'Autre')], default='question', max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('open', 'Ouvert'), ('answered', 'Répondu'), ('resolved', 'Résolu'), ('closed', 'Clos')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de support',
                'verbose_name_plural': 'Tickets de support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_support_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='complaints.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
